version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlw8
    ports:
      - '5432:5432'
    volumes:
      -  /var/lib/postgresql/data